export interface Track {
  id: string;
  title: string;
  artist: string;
  artwork?: string;
  videoId: string;
  duration: number;
  color: string;
}

const COLORS = [
  "#8B4513", "#A0522D", "#6B3A2A", "#704214", "#5C3317",
  "#7B3F00", "#8B5E3C", "#4A2C2A", "#6D4C41", "#795548",
  "#8D6E63", "#5D4037", "#3E2723", "#4E342E", "#6B4226",
  "#7B5B3A", "#9C6644", "#A67B5B", "#C19A6B", "#836953",
];

export const tracks: Track[] = [
  { id: "1", title: "36", artist: "Unknown", videoId: "GmytqWwPazE", duration: 239, color: COLORS[0] },
  { id: "2", title: "Batti", artist: "Unknown", videoId: "l7jf_VwYu94", duration: 189, color: COLORS[1] },
  { id: "3", title: "Shokeen", artist: "Rabb Da Radio 2", videoId: "SHqkcFNTJ4w", duration: 201, color: COLORS[2] },
  { id: "4", title: "BHANG BHAROSA", artist: "DeeVoy Singh", videoId: "QrM8BiBvnVM", duration: 184, color: COLORS[3] },
  { id: "5", title: "Bawa Bajte Hain", artist: "Unknown", videoId: "n5BHXaLvNfM", duration: 143, color: COLORS[4] },
  { id: "6", title: "Saza-E-Maut", artist: "feat. Raftaar", videoId: "49_iB_n7SOo", duration: 180, color: COLORS[5] },
  { id: "7", title: "Roll Up", artist: "feat. Badshah", videoId: "wo1IA3TyR6o", duration: 196, color: COLORS[6] },
  { id: "8", title: "Villain", artist: "feat. Karma, Ikka", videoId: "HrC8-heR1Xc", duration: 219, color: COLORS[7] },
  { id: "9", title: "Hum to yahape musafir hai", artist: "Advait Remix", videoId: "fAryOHdshXI", duration: 151, color: COLORS[8] },
  { id: "10", title: "Matkar Maya Ko Ahankar", artist: "Unknown", videoId: "V_08pyhaaTo", duration: 366, color: COLORS[9] },
  { id: "11", title: "Ek Din Pyaar", artist: "Unknown", videoId: "AGMVAUa0GYM", duration: 187, color: COLORS[10] },
  { id: "12", title: "Prarthana", artist: "Unknown", videoId: "CL08rrTSbus", duration: 200, color: COLORS[11] },
  { id: "13", title: "Paisa Hai Toh", artist: "Unknown", videoId: "RCvgKHadHrw", duration: 189, color: COLORS[12] },
  { id: "14", title: "I Guess", artist: "Unknown", videoId: "Jjw_85x3mOc", duration: 187, color: COLORS[13] },
  { id: "15", title: "101", artist: "Unknown", videoId: "oTs_0Ek-t-M", duration: 198, color: COLORS[14] },
  { id: "16", title: "Calling", artist: "Metro Boomin x Nav x A Boogie", videoId: "mh-KncHB6F4", duration: 120, color: COLORS[15] },
  { id: "17", title: "Dhundhala", artist: "Yashraj, Talwiinder, Dropped Out", videoId: "Xy1Pzu1yZGg", duration: 183, color: COLORS[16] },
  { id: "18", title: "Origami", artist: "G-Eazy feat. Connor Price", videoId: "oY3kPK0_I_U", duration: 121, color: COLORS[17] },
  { id: "19", title: "Jerk It Out", artist: "Caesars Palace (KIde Remix)", videoId: "gXHt27f4qdo", duration: 223, color: COLORS[18] },
  { id: "20", title: "Dirt Femme", artist: "Tove Lo", videoId: "l9_Y5Y7TUlU", duration: 2409, color: COLORS[19] },
  { id: "21", title: "Spinnin", artist: "Connor Price & Bens", videoId: "9vjDJrAkLHY", duration: 112, color: COLORS[0] },
  { id: "22", title: "I Don't Like Myself", artist: "Imagine Dragons", videoId: "iH1YfDu19KM", duration: 186, color: COLORS[1] },
  { id: "23", title: "Naina ki Talwar", artist: "MC SQUARE", videoId: "kpNYfy0Do0I", duration: 176, color: COLORS[2] },
  { id: "24", title: "Dip", artist: "Madrigal", videoId: "B0fJmlA49D4", duration: 240, color: COLORS[3] },
  { id: "25", title: "Chashmey", artist: "Anubhav Shukla aka Panther", videoId: "iKT3EvDiMlw", duration: 183, color: COLORS[4] },
  { id: "26", title: "BT Ho Gayi", artist: "Tanishq Singh aka Paradox", videoId: "ybRYNRcIuA4", duration: 166, color: COLORS[5] },
  { id: "27", title: "Sexy Lag raha tha", artist: "Wicked Sunny", videoId: "tXw0eJ6YEMc", duration: 175, color: COLORS[6] },
  { id: "28", title: "I Was Made For Lovin' You", artist: "Oliver Heldens (James Hype Remix)", videoId: "hH_HpuE6lE4", duration: 202, color: COLORS[7] },
  { id: "29", title: "City Life", artist: "Raghav Meattle", videoId: "Oge-Eaik0qY", duration: 178, color: COLORS[8] },
  { id: "30", title: "I'm Happy", artist: "Imagine Dragons", videoId: "-hyfscXeOHY", duration: 186, color: COLORS[9] },
  { id: "31", title: "Overthinking", artist: "Mabel, 24kGoldn", videoId: "qAZaDm-6jBI", duration: 214, color: COLORS[10] },
  { id: "32", title: "Maybe My Soulmate Died", artist: "iamnotshane", videoId: "S_KUxsFPpp8", duration: 112, color: COLORS[11] },
  { id: "33", title: "SAMJHO NA (NASAMAJH)", artist: "Aditya Rikhari", videoId: "MhXCj8E9CZU", duration: 170, color: COLORS[12] },
  { id: "34", title: "YAAD", artist: "Asim Azhar, Talha Anjum, Talhah Yunus", videoId: "a01oPKZQKoQ", duration: 277, color: COLORS[13] },
  { id: "35", title: "Maybe My Soulmate Died", artist: "iamnotshane (Lyrics)", videoId: "8jV_jrVdHRU", duration: 117, color: COLORS[14] },
  { id: "36", title: "Cold Heart", artist: "Elton John, Dua Lipa (PNAU Remix)", videoId: "O4efvhTKFZI", duration: 203, color: COLORS[15] },
  { id: "37", title: "Sooner Or Later", artist: "Years & Years", videoId: "Agmvw-POacY", duration: 251, color: COLORS[16] },
  { id: "38", title: "Bikhra", artist: "Rovalio & Abdul Hannan", videoId: "aRzbHxJZSTo", duration: 169, color: COLORS[17] },
  { id: "39", title: "G.O.M.D.", artist: "Sickick", videoId: "gGOMuIffC2k", duration: 131, color: COLORS[18] },
  { id: "40", title: "Sofia (Slowed)", artist: "Clairo", videoId: "5GG-PhBgqRA", duration: 224, color: COLORS[19] },
  { id: "41", title: "Somebody That I Used To Know", artist: "Gotye feat. Kimbra", videoId: "xgzKPE5tGKM", duration: 245, color: COLORS[0] },
  { id: "42", title: "As It Was (Mix)", artist: "Harry Styles, Ruth B., SZA", videoId: "TrO3LmN7nlo", duration: 920, color: COLORS[1] },
  { id: "43", title: "Sofia (Lo-Fi Version)", artist: "Clairo", videoId: "SSQ371L61wU", duration: 258, color: COLORS[2] },
  { id: "44", title: "Youngblood (Slowed + Reverb)", artist: "5SOS", videoId: "P_4AhFLM3OY", duration: 252, color: COLORS[3] },
  { id: "45", title: "Don't X What Is Love", artist: "Ed Sheeran x Jaymes Young", videoId: "8TmT_TUoPLs", duration: 209, color: COLORS[4] },
  { id: "46", title: "Riptide", artist: "The Chainsmokers", videoId: "sMlER3GMR7c", duration: 172, color: COLORS[5] },
  { id: "47", title: "SAD!", artist: "XXXTENTACION", videoId: "pgN-vvVVxMA", duration: 167, color: COLORS[6] },
  { id: "48", title: "Used To Know Me", artist: "Charli XCX", videoId: "dhYM5zMvFQk", duration: 175, color: COLORS[7] },
  { id: "49", title: "Chauffeur", artist: "Diljit Dosanjh x Tory Lanez", videoId: "6nxrllqnP2Q", duration: 203, color: COLORS[8] },
  { id: "50", title: "I Blame The World", artist: "Sasha Alex Sloan", videoId: "XzLV2KkQDcY", duration: 201, color: COLORS[9] },
  { id: "51", title: "Baby", artist: "Charli XCX", videoId: "ggrYaDxyrGM", duration: 170, color: COLORS[10] },
  { id: "52", title: "Everything But You", artist: "Clean Bandit feat. A7S", videoId: "Osq0RgGVwK8", duration: 250, color: COLORS[11] },
  { id: "53", title: "Long Drives", artist: "BoyWithUke", videoId: "FIILsSmS_nA", duration: 185, color: COLORS[12] },
  { id: "54", title: "Man On The Moon", artist: "Alan Walker x Benjamin Ingrosso", videoId: "1qrhnK6FGr0", duration: 183, color: COLORS[13] },
  { id: "55", title: "Beg For You", artist: "Charli XCX feat. Rina Sawayama", videoId: "hw_Gtwdnp1Q", duration: 183, color: COLORS[14] },
  { id: "56", title: "Green Light", artist: "ENISA", videoId: "pj_P82Y_LVk", duration: 198, color: COLORS[15] },
  { id: "57", title: "New Moon", artist: "MO", videoId: "DYZCXoPIH40", duration: 214, color: COLORS[16] },
  { id: "58", title: "Gradually", artist: "ASTN", videoId: "LHKh-PtGAZg", duration: 188, color: COLORS[17] },
  { id: "59", title: "Shut Off The Lights", artist: "Bastille", videoId: "RgrndTeoJFA", duration: 210, color: COLORS[18] },
  { id: "60", title: "Somebody That I Used To Know (Drill)", artist: "Gotye (Yoli Beatz)", videoId: "L7xzD-6q0mI", duration: 139, color: COLORS[19] },
  { id: "61", title: "Feels Like Summer", artist: "Childish Gambino", videoId: "F1B9Fk_SgI0", duration: 286, color: COLORS[0] },
  { id: "62", title: "G.O.M.D", artist: "J. Cole", videoId: "vHU6ZRQJ50Q", duration: 304, color: COLORS[1] },
  { id: "63", title: "Nishu", artist: "Ikka", videoId: "jtp0JV7eSaU", duration: 250, color: COLORS[2] },
  { id: "64", title: "OG", artist: "KR$NA", videoId: "wz7fnQMmABg", duration: 223, color: COLORS[3] },
  { id: "65", title: "Im Gone", artist: "Aitch ft. Lisa Murdoch", videoId: "oPF27cgTnsY", duration: 171, color: COLORS[4] },
  { id: "66", title: "Under Your Spell", artist: "Unknown", videoId: "0pzA32RY-0E", duration: 297, color: COLORS[5] },
  { id: "67", title: "Breathe", artist: "Unknown", videoId: "kbAwjyqa9BE", duration: 195, color: COLORS[6] },
  { id: "68", title: "Nice To Have", artist: "Unknown", videoId: "Mazm9eukUuE", duration: 233, color: COLORS[7] },
  { id: "69", title: "Figure Me Out", artist: "Unknown", videoId: "vES0laYFF1U", duration: 134, color: COLORS[8] },
  { id: "70", title: "Kitna Bechain Hoke", artist: "JalRaj", videoId: "Ob5gRnwbeHU", duration: 223, color: COLORS[9] },
  { id: "71", title: "THE NEXT RAP GOD 2", artist: "Dax", videoId: "hZGTYMzlwC4", duration: 1245, color: COLORS[10] },
  { id: "72", title: "SUPER GREMLIN Freestyle", artist: "Dax", videoId: "V4UqlfpChxs", duration: 218, color: COLORS[11] },
  { id: "73", title: "Knife Talk", artist: "Drake ft. 21 Savage", videoId: "XqpQpt_cmhE", duration: 245, color: COLORS[12] },
  { id: "74", title: "Super Gremlin", artist: "Kodak Black", videoId: "kiB9qk4gnt4", duration: 198, color: COLORS[13] },
  { id: "75", title: "Rose Bud", artist: "Tarsem Jassar, Wazir Patar", videoId: "1_vHAw6on98", duration: 179, color: COLORS[14] },
  { id: "76", title: "WE THE SAME", artist: "Addy Nagar", videoId: "v_6oYWGHT1U", duration: 210, color: COLORS[15] },
  { id: "77", title: "THATS WHAT I WANT", artist: "Lil Nas X", videoId: "QDYDRA5JPLE", duration: 162, color: COLORS[16] },
  { id: "78", title: "Lane Switcha", artist: "Skepta & Pop Smoke feat. A$AP Rocky", videoId: "PzSpQpqHKic", duration: 169, color: COLORS[17] },
  { id: "79", title: "Ride Da Night", artist: "Kevin Gates feat. Polo G", videoId: "UvkmSRzgGG4", duration: 169, color: COLORS[18] },
  { id: "80", title: "Red & Yellow", artist: "Lil Skies", videoId: "c1IMmAKJopU", duration: 226, color: COLORS[19] },
  { id: "81", title: "Flight to China", artist: "Wiz Khalifa feat. Toosii", videoId: "3vWDLqRazLg", duration: 204, color: COLORS[0] },
  { id: "82", title: "Small Talk (Remix)", artist: "Russ (by Nic D)", videoId: "gnZPZ-mX-zg", duration: 110, color: COLORS[1] },
  { id: "83", title: "SMALL TALK", artist: "Russ", videoId: "NyW_MLuM3e0", duration: 122, color: COLORS[2] },
  { id: "84", title: "Me and My Broken Heart", artist: "Rixton", videoId: "7JJfJgyHYwU", duration: 196, color: COLORS[3] },
  { id: "85", title: "Baliye Re", artist: "Sachet-Parampara, Stebin (Jersey)", videoId: "hZgckPZM7Hk", duration: 145, color: COLORS[4] },
  { id: "86", title: "Sufna Banke", artist: "Harvi", videoId: "YDuVz10Z7xU", duration: 177, color: COLORS[5] },
  { id: "87", title: "Late to the Party", artist: "Joyner Lucas & Ty Dolla $ign", videoId: "I_5Hi-LGSEA", duration: 209, color: COLORS[6] },
  { id: "88", title: "Your Heart", artist: "Joyner Lucas & J. Cole", videoId: "nD-Zu6aayS0", duration: 199, color: COLORS[7] },
  { id: "89", title: "Kehna Galat Galat", artist: "Madhur Sharma", videoId: "dPaZNGRcPK4", duration: 499, color: COLORS[8] },
  { id: "90", title: "Saadagi To Humari Zara Dekhiye", artist: "Sagar Bhatia (NFAK Cover)", videoId: "tyt_d6SN0nE", duration: 338, color: COLORS[9] },
  { id: "91", title: "Tere Siva Jag Mein", artist: "Darshan Raval (TADAP)", videoId: "TMNLnrp24_w", duration: 215, color: COLORS[10] },
  { id: "92", title: "Kinna Chir (Lofi Flip)", artist: "PropheC (Gravero)", videoId: "4NBdq1n5h78", duration: 255, color: COLORS[11] },
  { id: "93", title: "Paagla", artist: "Unknown", videoId: "U3c_h1_z8c0", duration: 266, color: COLORS[12] },
  { id: "94", title: "Kis Morh Te", artist: "Jyoti Nooran, B Praak (Qismat 2)", videoId: "rer21fKE1_I", duration: 164, color: COLORS[13] },
  { id: "95", title: "Shiddat Title Track", artist: "Manan Bhardwaj", videoId: "iSo9l950QLo", duration: 244, color: COLORS[14] },
  { id: "96", title: "Chitta", artist: "Manan Bhardwaj (Shiddat)", videoId: "CJq1hGSO89A", duration: 240, color: COLORS[15] },
  { id: "97", title: "Jug Jug Jeeve", artist: "Sachet-Parampara (Shiddat)", videoId: "Irw8llgSC3s", duration: 211, color: COLORS[16] },
  { id: "98", title: "These Days", artist: "Sidhu Moose Wala, Bohemia", videoId: "gnpw_Z-mBlY", duration: 212, color: COLORS[17] },
  { id: "99", title: "Pyar Di Kahani", artist: "Ammy Virk", videoId: "EphMiBecr_Y", duration: 337, color: COLORS[18] },
  { id: "100", title: "MERE WARGA", artist: "KAKA, Sukh-E", videoId: "e-TuBq5QTO0", duration: 286, color: COLORS[19] },
  { id: "101", title: "Chori Chori", artist: "Sunanda Sharma", videoId: "DhTY0XZeMFU", duration: 172, color: COLORS[0] },
  { id: "102", title: "LOVER", artist: "Diljit Dosanjh", videoId: "mH_LFkWxpI0", duration: 188, color: COLORS[1] },
  { id: "103", title: "Mehram", artist: "Sachet-Parampara (Jersey)", videoId: "ImEloUnWex8", duration: 165, color: COLORS[2] },
  { id: "104", title: "Feelinga", artist: "Garry Sandhu", videoId: "NDp3e0pcUrs", duration: 217, color: COLORS[3] },
  { id: "105", title: "Distance Love", artist: "Zehr Vibe", videoId: "45PR60pF_6w", duration: 205, color: COLORS[4] },
  { id: "106", title: "Somebody That I Used To Know", artist: "Gotye ft. Kimbra", videoId: "Q7DtJJSVPsk", duration: 281, color: COLORS[5] },
  { id: "107", title: "SPACESHIP", artist: "AP Dhillon, Shinda Kahlon", videoId: "RatDV50alQE", duration: 125, color: COLORS[6] },
  { id: "108", title: "You Right (Slowed + Reverb)", artist: "Doja Cat", videoId: "mitOlTHCFeI", duration: 275, color: COLORS[7] },
  { id: "109", title: "12 Bande", artist: "Varinder Brar", videoId: "yIR76Q3InbY", duration: 214, color: COLORS[8] },
  { id: "110", title: "Act Up", artist: "Rich Brian & Earthgang", videoId: "CW2X_R8Tj88", duration: 197, color: COLORS[9] },
  { id: "111", title: "INDUSTRY BABY", artist: "Lil Nas X, Jack Harlow", videoId: "UTHLKHL_whs", duration: 236, color: COLORS[10] },
  { id: "112", title: "FWMGAB", artist: "French Montana", videoId: "AndfQSUfoI0", duration: 191, color: COLORS[11] },
  { id: "113", title: "Numb (Joris Voorn Remix)", artist: "Elderbrook", videoId: "njPihnSWhR8", duration: 235, color: COLORS[12] },
  { id: "114", title: "Heat Waves (Slowed)", artist: "Glass Animals", videoId: "BhUthi9HGjg", duration: 206, color: COLORS[13] },
  { id: "115", title: "Two Moons (Slowed & Reverb)", artist: "BoyWithUke", videoId: "OCuhMuVkmPY", duration: 246, color: COLORS[14] },
  { id: "116", title: "In The Dark", artist: "Swae Lee feat. Jhene Aiko", videoId: "SmqeO5mj0ec", duration: 162, color: COLORS[15] },
  { id: "117", title: "Touch It (TikTok Remix)", artist: "Busta Rhymes", videoId: "v7ADTKFbUDs", duration: 271, color: COLORS[16] },
  { id: "118", title: "Welcome To The Rodeo", artist: "Lil Skies", videoId: "8A7bNJCjkx8", duration: 188, color: COLORS[17] },
  { id: "119", title: "Can't Help Falling In Love", artist: "Sody & Sarcastic Sounds", videoId: "3B5M8TyYpeg", duration: 168, color: COLORS[18] },
  { id: "120", title: "Golden", artist: "Harry Styles", videoId: "P3cffdsEXXw", duration: 210, color: COLORS[19] },
  { id: "121", title: "One Dance (Looped)", artist: "Wizkid", videoId: "rL7gtx5m84s", duration: 239, color: COLORS[0] },
  { id: "122", title: "Newbury Park", artist: "Lexi Jayde", videoId: "bMunyisZCKA", duration: 175, color: COLORS[1] },
  { id: "123", title: "Epic Post Malone Mashup", artist: "Sickick", videoId: "9DIqnFqYeTE", duration: 336, color: COLORS[2] },
  { id: "124", title: "MONTERO (Remix)", artist: "Lil Nas X (Ibrahim & Omer)", videoId: "GHRnsRDjlUk", duration: 143, color: COLORS[3] },
  { id: "125", title: "Dil Chahta Hai (Remix)", artist: "DJ NYK", videoId: "MpndWa8VosM", duration: 294, color: COLORS[4] },
  { id: "126", title: "Saathiya Remix", artist: "Sonu Nigam, A.R. Rahman", videoId: "zer08f9lF_c", duration: 176, color: COLORS[5] },
  { id: "127", title: "DIL SE REMIX", artist: "A.R. Rahman (Anshuman Sharma)", videoId: "-Tkh2KHL0go", duration: 175, color: COLORS[6] },
  { id: "128", title: "Talking To The Moon x Playdate", artist: "TikTok Edit", videoId: "woZyS_TGZ4I", duration: 234, color: COLORS[7] },
];

/** YouTube thumbnail URL for a video */
export function getYouTubeThumbnail(videoId: string): string {
  return `https://i.ytimg.com/vi_webp/${videoId}/mqdefault.webp`;
}

/** Circular index into the track list */
export function wrapIndex(index: number, length: number): number {
  return ((index % length) + length) % length;
}

/** Get the 5 visible tracks centered on currentIndex */
export function getVisibleTracks(currentIndex: number): Track[] {
  const len = tracks.length;
  return [
    tracks[wrapIndex(currentIndex - 2, len)],
    tracks[wrapIndex(currentIndex - 1, len)],
    tracks[wrapIndex(currentIndex, len)],
    tracks[wrapIndex(currentIndex + 1, len)],
    tracks[wrapIndex(currentIndex + 2, len)],
  ];
}
